#! /usr/bin/env python3

import argparse
import datetime

parser = argparse.ArgumentParser()
parser.add_argument("--initial-savings"           , type=float, metavar="<USD>"  )
parser.add_argument("--working-annual-return-rate", type=float, metavar="<rate>")
parser.add_argument("--retired-annual-return-rate", type=float, metavar="<rate>")
parser.add_argument("--inflation"                 , type=float, metavar="<rate>")
parser.add_argument("--working"                   , type=float, metavar="<years>")
parser.add_argument("--retired"                   , type=float, metavar="<years>")
parser.add_argument("--working-annual-savings"    , type=float, metavar="<USD>"  )
parser.add_argument("--retired-annual-withdraw"   , type=float, metavar="<USD>"  )
parser.add_argument("--verbose"                   , action="store_true")

args = parser.parse_args()

if args.initial_savings == None:
    print( \
'''\
Initial savings:
  Let's assume $0
''')
    args.initial_savings = .0

if args.working_annual_return_rate == None:
    print( \
'''\
Annual return rate while working:
  Average annual return on the S&P 500 from 1928 to 2017 is .114
  Average 1990-2017 is .111
  Average 2000-2017 is .068

  Source: https://seekingalpha.com/instablog/605212-robert-allan-schwartz/4831186-annual-returns-s-and-p-500-1928-2015
          https://www.google.com/search?q=s%26p+2016+return&oq=s%26p+2016+return
          https://dqydj.com/2017-sp-500-return/

  Let's assume .07
''')
    args.working_annual_return_rate = .07

if args.retired_annual_return_rate == None:
    print( \
'''\
Annual return rate while retired:
  Average annual return on (3mo T-Bills, 10y T-Bonds) from 1928 to 2017 is (.0344, .0515)
  Average 1990-2017 is (.0279, .0637)
  Average 2000-2017 is (.0166, .0556)

  Bloomberg Barclays US Aggregate Bond TR USD average annual return 2003-2017: .0388

  Source: http://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/histretSP.html
          http://performance.morningstar.com/Performance/index-c/performance-return.action?t=XIUSA000MC

  Let's assume .05
''')
    args.retired_annual_return_rate = .05

if args.inflation == None:
    print( \
'''\
Inflation:
  Average annual inflation from 1914 to 2017 in the USA is .0318
  Average 1990-2017 is .025

  Source: https://inflationdata.com/Inflation/Inflation/DecadeInflation.asp

  Let's assume .03
''')
    args.inflation = .03

if args.working == None:
    print( \
'''\
Working years:
  Let's assume 35
''')
    args.working = 35

if args.retired == None:
    print( \
'''\
Years in retirement:
  Let's assume 30
''')
    args.retired = 30

if args.working_annual_savings == None:
    print( \
'''\
Working annual savings:
  Let's assume $6000
''')
    args.working_annual_savings = 6000.0

if args.retired_annual_withdraw == None:
    print( \
'''\
Retired annual withdraw:
  Let's assume $24000
''')
    args.retired_annual_withdraw = 24000.0

currentyear = datetime.date.today().year

initial_savings            = args.initial_savings
working                    = args.working
working_annual_return_rate = args.working_annual_return_rate
retired_annual_return_rate = args.retired_annual_return_rate
inflation                  = args.inflation
working                    = args.working
retired                    = args.retired
working_annual_savings     = args.working_annual_savings
retired_annual_withdraw    = args.retired_annual_withdraw
verbose                    = args.verbose

savings=initial_savings
for year in range(1, working+1):
    return_ = savings * working_annual_return_rate
    savings += return_
    savings += working_annual_savings
    savings *= (1-inflation)

    if verbose:
        print("Year: %04d, Savings: $%9.0f, Return: $ %7.0f" % (currentyear + year, savings, return_))
    else:
        print("Year: %04d, Savings: $%9.0f" % (currentyear + year, savings))

print("Retirement start:")

for year in range(1, retired+1):
    savings -= retired_annual_withdraw
    return_ = savings * retired_annual_return_rate
    savings += return_
    savings *= (1-inflation)

    if verbose:
        print("Year: %04d, Savings: $%9.0f, Return: $ %7.0f" % (currentyear + working + year, savings, return_))
    else:
        print("Year: %04d, Savings: $%9.0f" % (currentyear + working + year, savings))
