#! /usr/bin/env python3

import argparse
import datetime

parser = argparse.ArgumentParser()
parser.add_argument("--initial-savings"        , type=float, metavar="<USD>"  )
parser.add_argument("--interest-working"       , type=float, metavar="<ratio>")
parser.add_argument("--interest-retired"       , type=float, metavar="<ratio>")
parser.add_argument("--inflation"              , type=float, metavar="<ratio>")
parser.add_argument("--working"                , type=float, metavar="<years>")
parser.add_argument("--retired"                , type=float, metavar="<years>")
parser.add_argument("--working-yearly-savings" , type=float, metavar="<USD>"  )
parser.add_argument("--retired-yearly-withdraw", type=float, metavar="<USD>"  )
parser.add_argument("--capital-gains"          , type=float, metavar="<ratio>")
parser.add_argument("--verbose"                , action="store_true")

args = parser.parse_args()

if args.initial_savings == None:
    print( \
'''\
Initial savings:
  Let's assume $0
''')
    args.initial_savings = .0

if args.interest_working == None:
    print( \
'''\
Interest working:
  Average yearly return on the S&P 500 from 1928 to 2017 is .114
  Average 1990-2017 is .111
  Average 2000-2017 is .068

  Source: https://seekingalpha.com/instablog/605212-robert-allan-schwartz/4831186-annual-returns-s-and-p-500-1928-2015
          https://www.google.com/search?q=s%26p+2016+return&oq=s%26p+2016+return
          https://dqydj.com/2017-sp-500-return/

  Let's assume .07
''')
    args.interest_working = .07

if args.interest_retired == None:
    print( \
'''\
Interest retired:
  Average yearly return on (3mo T-Bills, 10y T-Bonds) from 1928 to 2017 is (.0344, .0515)
  Average 1990-2017 is (.0279, .0637)
  Average 2000-2017 is (.0166, .0556)

  Bloomberg Barclays US Aggregate Bond TR USD average yearly return 2003-2017: .0388

  Source: http://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/histretSP.html
          http://performance.morningstar.com/Performance/index-c/performance-return.action?t=XIUSA000MC

  Let's assume .05
''')
    args.interest_retired = .05

if args.inflation == None:
    print( \
'''\
Inflation:
  Average yearly inflation from 1914 to 2017 in the USA is .0318
  Average 1990-2017 is .025

  Source: https://inflationdata.com/Inflation/Inflation/DecadeInflation.asp

  Let's assume .03
''')
    args.inflation = .03

if args.working == None:
    print( \
'''\
Working years:
  Let's assume 35
''')
    args.working = 35

if args.retired == None:
    print( \
'''\
Years in retirement:
  Let's assume 30
''')
    args.retired = 30

if args.working_yearly_savings == None:
    print( \
'''\
Working yearly savings:
  Let's assume $6000
''')
    args.working_yearly_savings = 6000.0

if args.retired_yearly_withdraw == None:
    print( \
'''\
Retired yearly withdraw:
  Let's assume $24000
''')
    args.retired_yearly_withdraw = 24000.0

if args.capital_gains == None:
    print( \
'''\
Capital gain tax:

  Single Income: $0–$38,600       Capital gain tax: .0
  Single Income: $38,601–$425,800 Capital gain tax: .15
  Single Income: Over $425,800    Capital gain tax: .20

  Source: https://en.wikipedia.org/wiki/Capital_gains_tax_in_the_United_States

  Let's assume .0
''')
    args.capital_gains = .0

currentyear = datetime.date.today().year

initial_savings         = args.initial_savings
working                 = args.working
interest_working        = args.interest_working
interest_retired        = args.interest_retired
inflation               = args.inflation
working                 = args.working
retired                 = args.retired
working_yearly_savings  = args.working_yearly_savings
retired_yearly_withdraw = args.retired_yearly_withdraw
capital_gains           = args.capital_gains
verbose                 = args.verbose

savings=initial_savings
for year in range(1, working+1):
    return_before_tax = savings*interest_working
    return_after_tax = return_before_tax * (1 - capital_gains)
    savings += return_after_tax
    savings += working_yearly_savings
    savings *= (1-inflation)

    if verbose:
        print("Year: %04d, Savings: $%9.0f, Return before tax: $ %7.0f, Capital gain tax: $ %6.0f, Return after tax: $ %7.0f" % (currentyear + year, savings, return_before_tax, return_before_tax*capital_gains, return_after_tax))
    else:
        print("Year: %04d, Savings: $%9.0f" % (currentyear + year, savings))

print("Retirement start:")

for year in range(1, retired+1):
    savings -= retired_yearly_withdraw
    return_before_tax = savings * interest_retired
    return_after_tax = return_before_tax * (1 - capital_gains)
    savings += return_after_tax
    savings *= (1-inflation)

    if verbose:
        print("Year: %04d, Savings: $%9.0f, Return before tax: $ %7.0f, Capital gain tax: $ %6.0f, Return after tax: $ %7.0f" % (currentyear + working + year, savings, return_before_tax, return_before_tax*capital_gains, return_after_tax))
    else:
        print("Year: %04d, Savings: $%9.0f" % (currentyear + working + year, savings))
